# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UI_Client(object):
    def setupUi(self, UI_Client):
        UI_Client.setObjectName("UI_Client")
        UI_Client.resize(904, 679)
        UI_Client.setAutoFillBackground(True)
        UI_Client.setDocumentMode(False)
        UI_Client.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(UI_Client)
        self.centralwidget.setObjectName("centralwidget")
        self.listView_2 = QtWidgets.QListView(self.centralwidget)
        self.listView_2.setGeometry(QtCore.QRect(10, 10, 651, 541))
        self.listView_2.setObjectName("listView_2")
        self.listView = QtWidgets.QListView(self.centralwidget)
        self.listView.setGeometry(QtCore.QRect(670, 10, 231, 541))
        self.listView.setObjectName("listView")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(670, 560, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(790, 560, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(10, 560, 571, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName("textEdit")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(590, 560, 71, 71))
        self.pushButton_3.setObjectName("pushButton_3")
        UI_Client.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(UI_Client)
        self.menubar.setEnabled(True)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 904, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        UI_Client.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(UI_Client)
        self.statusbar.setEnabled(True)
        self.statusbar.setObjectName("statusbar")
        UI_Client.setStatusBar(self.statusbar)
        self.action = QtWidgets.QAction(UI_Client)
        self.action.setObjectName("action")
        self.action_2 = QtWidgets.QAction(UI_Client)
        self.action_2.setObjectName("action_2")
        self.action_3 = QtWidgets.QAction(UI_Client)
        self.action_3.setObjectName("action_3")
        self.menu.addAction(self.action)
        self.menu_2.addAction(self.action_2)
        self.menu_2.addAction(self.action_3)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(UI_Client)
        QtCore.QMetaObject.connectSlotsByName(UI_Client)

    def retranslateUi(self, UI_Client):
        _translate = QtCore.QCoreApplication.translate
        UI_Client.setWindowTitle(_translate("UI_Client", "UI_Client"))
        self.pushButton.setText(_translate("UI_Client", "Добавить"))
        self.pushButton_2.setText(_translate("UI_Client", "Удалить"))
        self.textEdit.setPlaceholderText(_translate("UI_Client", "Введите сообщение для отправки"))
        self.pushButton_3.setText(_translate("UI_Client", "Отправить"))
        self.menu.setTitle(_translate("UI_Client", "Файл"))
        self.menu_2.setTitle(_translate("UI_Client", "Контакты"))
        self.action.setText(_translate("UI_Client", "Выход"))
        self.action_2.setText(_translate("UI_Client", "Добавить контакт"))
        self.action_3.setText(_translate("UI_Client", "Удалить контакт"))
