# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UI_Client(object):
    def setupUi(self, UI_Client):
        UI_Client.setObjectName("UI_Client")
        UI_Client.resize(906, 675)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(UI_Client.sizePolicy().hasHeightForWidth())
        UI_Client.setSizePolicy(sizePolicy)
        UI_Client.setAutoFillBackground(True)
        UI_Client.setDocumentMode(False)
        UI_Client.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(UI_Client)
        self.centralwidget.setObjectName("centralwidget")
        self.chat_history = QtWidgets.QListView(self.centralwidget)
        self.chat_history.setGeometry(QtCore.QRect(10, 30, 651, 521))
        self.chat_history.setObjectName("chat_history")
        self.chats_list = QtWidgets.QListView(self.centralwidget)
        self.chats_list.setGeometry(QtCore.QRect(670, 30, 231, 521))
        self.chats_list.setObjectName("chats_list")
        self.msg_area = QtWidgets.QTextEdit(self.centralwidget)
        self.msg_area.setGeometry(QtCore.QRect(10, 560, 571, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.msg_area.setFont(font)
        self.msg_area.setObjectName("msg_area")
        self.send_msg = QtWidgets.QPushButton(self.centralwidget)
        self.send_msg.setGeometry(QtCore.QRect(590, 560, 71, 71))
        self.send_msg.setObjectName("send_msg")
        self.chat_label = QtWidgets.QLabel(self.centralwidget)
        self.chat_label.setGeometry(QtCore.QRect(10, 10, 651, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.chat_label.setFont(font)
        self.chat_label.setObjectName("chat_label")
        self.search_cont = QtWidgets.QLineEdit(self.centralwidget)
        self.search_cont.setGeometry(QtCore.QRect(670, 560, 231, 31))
        self.search_cont.setObjectName("search_cont")
        UI_Client.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(UI_Client)
        self.menubar.setEnabled(True)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 906, 21))
        self.menubar.setObjectName("menubar")
        self.main_menu = QtWidgets.QMenu(self.menubar)
        self.main_menu.setObjectName("main_menu")
        UI_Client.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(UI_Client)
        self.statusbar.setEnabled(True)
        self.statusbar.setObjectName("statusbar")
        UI_Client.setStatusBar(self.statusbar)
        self.action = QtWidgets.QAction(UI_Client)
        self.action.setObjectName("action")
        self.main_menu.addAction(self.action)
        self.menubar.addAction(self.main_menu.menuAction())

        self.retranslateUi(UI_Client)
        QtCore.QMetaObject.connectSlotsByName(UI_Client)

    def retranslateUi(self, UI_Client):
        _translate = QtCore.QCoreApplication.translate
        UI_Client.setWindowTitle(_translate("UI_Client", "UI_Client"))
        self.msg_area.setPlaceholderText(_translate("UI_Client", "Введите сообщение для отправки..."))
        self.send_msg.setText(_translate("UI_Client", "Отправить"))
        self.chat_label.setText(_translate("UI_Client", "Чат с пользователем"))
        self.search_cont.setPlaceholderText(_translate("UI_Client", "Поиск...."))
        self.main_menu.setTitle(_translate("UI_Client", "Файл"))
        self.action.setText(_translate("UI_Client", "Выход"))
